### ISSUE TITLE
úkol 6 - půjčovna

### ISSUE THREAD

**Issue by kubincom** [kubincom/python01_2022#6]
Ahoj Ondro,

posílám úkol 6.
https://github.com/kubincom/python01_2022/blob/main/ukol6_pujcovna_aut.py
Bylo to trápení, ale nakonec jsem na to snad přišla :)

Díky za check.

Míša

**Comment by pixelneo** [comment]
Ahoj, mas to spravne! :-) 

Jen mala poznamka, nahore jsou nejake importovane moduly:
```
from dataclasses import replace
from enum import auto
from turtle import  shapesize
```
tipuji, ze je tam nejak automaticky dodalo Visual Studio Code. Nevadi, ze tam jsou, ale nejsou potreba :-)
